import { NextRequest, NextResponse } from "next/server";
import connectDB from "@/lib/db";
import Room from "@/models/Room";
import type { RoomType } from "@/types/data";

//Note: for creating a new Room, we don't need to include _id in the request body,
//Note: as it will be automatically generated by MongoDB. However, we can include _id in the request body for updating an existing Room.
interface CreateRoomRequest {
  name: string;
  type: RoomType;
  capacity: number;
  price: number;
  description?: string;
  imageUrl?: string;
  available?: boolean;
}

export async function GET(request: NextRequest) {
  try {
    await connectDB();

    const searchParams = request.nextUrl.searchParams;
    const type = searchParams.get("type");
    const available = searchParams.get("available");

    const filter: { type?: RoomType; available?: boolean } = {};

    if (type) {
      if (type !== "SMALL" && type !== "CONFERENCE") {
        return NextResponse.json(
          {
            success: false,
            error: {
              code: "VALIDATION_ERROR",
              message: `${type} is not a valid room type`,
            },
          },
          { status: 400 },
        );
      }
      filter.type = type as RoomType;
    }

    if (available !== null) {
      if (available !== "true" && available !== "false") {
        return NextResponse.json(
          {
            success: false,
            error: {
              code: "VALIDATION_ERROR",
              message: "Available must be either true or false",
            },
          },
          { status: 400 },
        );
      }
      filter.available = available === "true";
    }

    const rooms = await Room.find(filter).sort({ createdAt: -1 }).lean();

    return NextResponse.json(
      {
        success: true,
        data: rooms,
        count: rooms.length,
      },
      { status: 200 },
    );
  } catch {
    return NextResponse.json(
      {
        success: false,
        error: {
          code: "INTERNAL_SERVER_ERROR",
          message: "Internal server error",
        },
      },
      { status: 500 },
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    await connectDB();

    const body: CreateRoomRequest = await request.json();

    if (
      !body.name ||
      !body.type ||
      body.capacity === undefined ||
      body.price === undefined
    ) {
      return NextResponse.json(
        {
          success: false,
          error: {
            code: "VALIDATION_ERROR",
            message: "Name, type, capacity, and price are required",
          },
        },
        { status: 400 },
      );
    }

    if (body.capacity < 1) {
      return NextResponse.json(
        {
          success: false,
          error: {
            code: "VALIDATION_ERROR",
            message: "Capacity must be at least 1",
          },
        },
        { status: 400 },
      );
    }

    if (body.price < 0) {
      return NextResponse.json(
        {
          success: false,
          error: {
            code: "VALIDATION_ERROR",
            message: "Price cannot be negative",
          },
        },
        { status: 400 },
      );
    }

    const newRoom = await Room.create(body);

    return NextResponse.json(
      {
        success: true,
        data: newRoom,
        message: "Room created successfully",
      },
      { status: 201 },
    );
  } catch {
    return NextResponse.json(
      {
        success: false,
        error: {
          code: "INTERNAL_SERVER_ERROR",
          message: "Failed to create room",
        },
      },
      { status: 500 },
    );
  }
}
